export const dynamic = 'force-dynamic';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import './globals.css';
import { Nunito } from 'next/font/google';
import { LanguageProvider, SupportedLang } from './context/LanguageProvider';
import { Header } from '@/widgets/header';

const font = Nunito({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const lang = (cookieStore.get('lang')?.value || 'en') as SupportedLang;

  return (
    <html
      lang={lang}
      className={font.className}
    >
      <body className='gradient-bg mx-auto min-h-screen w-[90%] md:w-7/10 lg:w-6/10'>
        <LanguageProvider savedLang={lang}>
          <Header />
          <main className='mx-auto flex w-[90%] flex-col items-center py-4 md:w-7/10 md:py-6 lg:py-8'>
            {children}
          </main>
        </LanguageProvider>
      </body>
    </html>
  );
}
